apiVersion: skaffold/v4beta5
kind: Config
build:
  artifacts:
    - image: juniorotero/client
      context: client
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: juniorotero/comments
      context: comments
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: juniorotero/moderation
      context: moderation
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: juniorotero/query
      context: query
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: juniorotero/junior-event-bus
      context: event-bus
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: juniorotero/junior-posts
      context: posts
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
